export type TopicDomain =
  | "foreign_policy"
  | "politics"
  | "technology"
  | "health"
  | "business"
  | "media";

export interface TopicTaxonomyEntry {
  slug: string;
  name: string;
  domain: TopicDomain;
  description: string;
  aliases: string[];
}

/**
 * Controlled taxonomy finalized from local topic discovery and curation.
 *
 * These topics are intentionally narrower than broad buckets like "Politics"
 * or "Health", but broad enough to support stance and viewpoint-over-time
 * analysis across transcript chunks.
 */
export const CONTROLLED_TOPIC_TAXONOMY: TopicTaxonomyEntry[] = [
  {
    slug: "big_tech_employment_and_layoffs",
    name: "Big Tech Employment and Layoffs",
    domain: "business",
    description: "Conversations and takes on Big Tech Employment and Layoffs.",
    aliases: [
      "tech employment",
      "employment layoffs",
      "big tech employment",
      "tech employment layoffs",
      "big tech employment and layoffs",
    ],
  },
  {
    slug: "bitcoin_crypto_and_digital_assets",
    name: "Bitcoin Crypto and Digital Assets",
    domain: "business",
    description:
      "Where the creator weighs in on Bitcoin Crypto and Digital Assets.",
    aliases: [
      "crypto",
      "bitcoin",
      "bitcoin crypto",
      "crypto digital",
      "digital assets",
      "crypto digital assets",
      "bitcoin crypto digital",
      "bitcoin crypto and digital assets",
    ],
  },
  {
    slug: "commercial_real_estate_debt_crisis",
    name: "Commercial Real Estate Debt Crisis",
    domain: "business",
    description:
      "Analysis and commentary on Commercial Real Estate Debt Crisis.",
    aliases: [
      "debt crisis",
      "estate debt",
      "real estate",
      "commercial real",
      "real estate debt",
      "estate debt crisis",
      "commercial real estate",
      "commercial real estate debt crisis",
    ],
  },
  {
    slug: "prediction_markets_and_event_betting",
    name: "Prediction Markets and Event Betting",
    domain: "business",
    description: "Segments that dig into Prediction Markets and Event Betting.",
    aliases: [
      "event betting",
      "markets event",
      "capital markets",
      "prediction markets",
      "markets event betting",
      "prediction markets event",
      "prediction markets and event betting",
    ],
  },
  {
    slug: "public_markets_and_ipo_policy",
    name: "Public Markets and IPO Policy",
    domain: "business",
    description: "Conversations and takes on Public Markets and IPO Policy.",
    aliases: [
      "ipo policy",
      "markets ipo",
      "public markets",
      "markets ipo policy",
      "public markets ipo",
      "public markets and ipo policy",
    ],
  },
  {
    slug: "return_to_office_and_remote_work_policy",
    name: "Return to Office and Remote Work Policy",
    domain: "business",
    description:
      "Where the creator weighs in on Return to Office and Remote Work Policy.",
    aliases: [
      "remote work",
      "work policy",
      "jamie diamond",
      "office remote",
      "return office",
      "office remote work",
      "remote work policy",
      "return office remote",
      "return to office and remote work policy",
    ],
  },
  {
    slug: "saas_gross_margins_and_valuation",
    name: "SaaS Gross Margins and Valuation",
    domain: "business",
    description: "Analysis and commentary on SaaS Gross Margins and Valuation.",
    aliases: [
      "saas gross",
      "gross margin",
      "gross margins",
      "margins valuation",
      "saas gross margins",
      "gross margins valuation",
      "saas gross margins and valuation",
    ],
  },
  {
    slug: "silicon_valley_bank_and_regional_banking_crisis",
    name: "Silicon Valley Bank and Regional Banking Crisis",
    domain: "business",
    description:
      "Segments that dig into Silicon Valley Bank and Regional Banking Crisis.",
    aliases: [
      "run bank",
      "bank regional",
      "banking crisis",
      "regional banking",
      "unrealized losses",
      "silicon valley bank",
      "bank regional banking",
      "regional banking crisis",
      "silicon valley bank and regional banking crisis",
    ],
  },
  {
    slug: "small_business_financing_and_sba_policy",
    name: "Small Business Financing and SBA Policy",
    domain: "business",
    description:
      "Conversations and takes on Small Business Financing and SBA Policy.",
    aliases: [
      "sba policy",
      "financing sba",
      "small businesses",
      "business financing",
      "financing sba policy",
      "business financing sba",
      "small business financing",
      "small business financing and sba policy",
    ],
  },
  {
    slug: "startup_founder_and_vc_fundraising",
    name: "Startup Founder and VC Fundraising",
    domain: "business",
    description:
      "Where the creator weighs in on Startup Founder and VC Fundraising.",
    aliases: [
      "founder vc",
      "founders fund",
      "vc fundraising",
      "startup founder",
      "startup founder vc",
      "founder vc fundraising",
      "startup founder and vc fundraising",
    ],
  },
  {
    slug: "startup_fundraising_and_capital_allocation",
    name: "Startup Fundraising and Capital Allocation",
    domain: "business",
    description:
      "Analysis and commentary on Startup Fundraising and Capital Allocation.",
    aliases: [
      "money going",
      "raise money",
      "spend money",
      "capital allocation",
      "fundraising capital",
      "startup fundraising",
      "startup fundraising capital",
      "fundraising capital allocation",
      "startup fundraising and capital allocation",
    ],
  },
  {
    slug: "venture_capital_fund_economics",
    name: "Venture Capital Fund Economics",
    domain: "business",
    description: "Segments that dig into Venture Capital Fund Economics.",
    aliases: [
      "hedge fund",
      "capital fund",
      "venture fund",
      "fund economics",
      "venture capital",
      "venture capital fund",
      "capital fund economics",
      "venture capital fund economics",
    ],
  },
  {
    slug: "workplace_politics_and_company_speech_policy",
    name: "Workplace Politics and Company Speech Policy",
    domain: "business",
    description:
      "Conversations and takes on Workplace Politics and Company Speech Policy.",
    aliases: [
      "safe space",
      "speech policy",
      "company speech",
      "politics company",
      "workplace politics",
      "company speech policy",
      "politics company speech",
      "workplace politics company",
      "workplace politics and company speech policy",
    ],
  },
  {
    slug: "brics_geopolitics",
    name: "Brics Geopolitics",
    domain: "foreign_policy",
    description: "Where the creator weighs in on Brics Geopolitics.",
    aliases: ["brics geopolitics"],
  },
  {
    slug: "china_taiwan_conflict",
    name: "Defend Taiwan",
    domain: "foreign_policy",
    description: "Analysis and commentary on Defend Taiwan.",
    aliases: [
      "china taiwan",
      "taiwan china",
      "defend taiwan",
      "taiwan conflict",
      "china taiwan conflict",
    ],
  },
  {
    slug: "defense_budget",
    name: "Defense Budget",
    domain: "foreign_policy",
    description: "Segments that dig into Defense Budget.",
    aliases: ["defense budget"],
  },
  {
    slug: "drone_warfare_and_defense_tech",
    name: "Drone Warfare and Defense Tech",
    domain: "foreign_policy",
    description: "Conversations and takes on Drone Warfare and Defense Tech.",
    aliases: [
      "drone",
      "defense tech",
      "drone warfare",
      "warfare defense",
      "department defense",
      "warfare defense tech",
      "drone warfare defense",
      "drone warfare and defense tech",
    ],
  },
  {
    slug: "emerging_markets_and_sovereign_debt_crises",
    name: "Emerging Markets and Sovereign Debt Crises",
    domain: "foreign_policy",
    description:
      "Where the creator weighs in on Emerging Markets and Sovereign Debt Crises.",
    aliases: [
      "sri lanka",
      "sri lankan",
      "debt crises",
      "sovereign debt",
      "emerging market",
      "emerging markets",
      "markets sovereign",
      "sovereign debt crises",
      "markets sovereign debt",
      "emerging markets sovereign",
      "emerging markets and sovereign debt crises",
    ],
  },
  {
    slug: "foreign_policy_establishment",
    name: "Foreign Policy Establishment",
    domain: "foreign_policy",
    description: "Analysis and commentary on Foreign Policy Establishment.",
    aliases: ["foreign policy establishment"],
  },
  {
    slug: "great_power_politics",
    name: "Great Power Politics",
    domain: "foreign_policy",
    description: "Segments that dig into Great Power Politics.",
    aliases: ["great power politics"],
  },
  {
    slug: "india_foreign_policy",
    name: "India Foreign Policy",
    domain: "foreign_policy",
    description: "Conversations and takes on India Foreign Policy.",
    aliases: ["india foreign policy"],
  },
  {
    slug: "military_alliances",
    name: "Military Alliances",
    domain: "foreign_policy",
    description: "Where the creator weighs in on Military Alliances.",
    aliases: ["military alliances"],
  },
  {
    slug: "adhd_focus_and_treatment",
    name: "ADHD Focus and Treatment",
    domain: "health",
    description: "Analysis and commentary on ADHD Focus and Treatment.",
    aliases: ["adhd focus and treatment"],
  },
  {
    slug: "adhd_stimulant_medication",
    name: "ADHD Stimulant Medication",
    domain: "health",
    description: "Segments that dig into ADHD Stimulant Medication.",
    aliases: ["adhd stimulant medication"],
  },
  {
    slug: "advanced_glycation",
    name: "Advanced Glycation",
    domain: "health",
    description: "Conversations and takes on Advanced Glycation.",
    aliases: ["glycation", "advanced glycation", "glycation products"],
  },
  {
    slug: "animal_behavior_and_human_pet_relationships",
    name: "Animal Behavior and Human Pet Relationships",
    domain: "health",
    description:
      "Where the creator weighs in on Animal Behavior and Human Pet Relationships.",
    aliases: [
      "dog dogs",
      "human pet",
      "behavior human",
      "animal behavior",
      "pet relationships",
      "behavior human pet",
      "animal behavior human",
      "human pet relationships",
      "animal behavior and human pet relationships",
    ],
  },
  {
    slug: "attention_focus_and_cognitive_control",
    name: "Attention Focus and Cognitive Control",
    domain: "health",
    description:
      "Analysis and commentary on Attention Focus and Cognitive Control.",
    aliases: [
      "pay attention",
      "attention focus",
      "focus cognitive",
      "paying attention",
      "cognitive control",
      "directed attention",
      "focus cognitive control",
      "attention focus cognitive",
      "attention focus and cognitive control",
    ],
  },
  {
    slug: "bdnf_and_neuroplasticity",
    name: "BDNF and Neuroplasticity",
    domain: "health",
    description: "Segments that dig into BDNF and Neuroplasticity.",
    aliases: [
      "brain cells",
      "increase bdnf",
      "increases bdnf",
      "bdnf neuroplasticity",
      "bdnf and neuroplasticity",
    ],
  },
  {
    slug: "behavior_change_and_self_improvement",
    name: "Behavior Change and Self Improvement",
    domain: "health",
    description:
      "Conversations and takes on Behavior Change and Self Improvement.",
    aliases: [
      "change self",
      "self change",
      "behavior change",
      "self improvement",
      "behavior change self",
      "change self improvement",
      "behavior change and self improvement",
    ],
  },
  {
    slug: "big_tech_attention_economy",
    name: "Big Tech Attention Economy",
    domain: "health",
    description: "Where the creator weighs in on Big Tech Attention Economy.",
    aliases: ["big tech attention economy"],
  },
  {
    slug: "bipolar_disorder_and_mood_disorders",
    name: "Bipolar Disorder and Mood Disorders",
    domain: "health",
    description:
      "Analysis and commentary on Bipolar Disorder and Mood Disorders.",
    aliases: [
      "disorder mood",
      "manic episodes",
      "mood disorders",
      "people bipolar",
      "bipolar disorder",
      "bipolar disorder mood",
      "disorder mood disorders",
      "bipolar disorder and mood disorders",
    ],
  },
  {
    slug: "blood_brain_barrier_and_cognitive_health",
    name: "Blood Brain Barrier and Cognitive Health",
    domain: "health",
    description:
      "Segments that dig into Blood Brain Barrier and Cognitive Health.",
    aliases: [
      "blood brain",
      "white matter",
      "brain barrier",
      "regions brain",
      "cognitive health",
      "barrier cognitive",
      "cognitive function",
      "blood brain barrier",
      "brain barrier cognitive",
      "barrier cognitive health",
      "blood brain barrier and cognitive health",
    ],
  },
  {
    slug: "brain_health",
    name: "Brain Health",
    domain: "health",
    description: "Conversations and takes on Brain Health.",
    aliases: ["brain health"],
  },
  {
    slug: "carbohydrate_intake_strategy",
    name: "Carbohydrate Intake Strategy",
    domain: "health",
    description: "Where the creator weighs in on Carbohydrate Intake Strategy.",
    aliases: [
      "carbohydrate",
      "carbohydrates",
      "intake strategy",
      "eat carbohydrates",
      "carbohydrate intake",
      "carbohydrates going",
      "consume carbohydrates",
      "carbohydrate intake strategy",
    ],
  },
  {
    slug: "cardio_vo2max",
    name: "Cardio VO2 Max",
    domain: "health",
    description: "Analysis and commentary on Cardio VO2 Max.",
    aliases: [
      "vo2",
      "cardio",
      "vo2 max",
      "going run",
      "cardio vo2",
      "cardio vo2max",
      "cardio vo2 max",
      "muscular endurance",
    ],
  },
  {
    slug: "chronic_pain_and_pain_management",
    name: "Chronic Pain and Pain Management",
    domain: "health",
    description: "Segments that dig into Chronic Pain and Pain Management.",
    aliases: [
      "pain pain",
      "chronic pain",
      "experience pain",
      "pain management",
      "chronic pain pain",
      "pain pain management",
      "chronic pain and pain management",
    ],
  },
  {
    slug: "chronic_pain_management",
    name: "Chronic Pain Management",
    domain: "health",
    description: "Conversations and takes on Chronic Pain Management.",
    aliases: ["chronic pain management"],
  },
  {
    slug: "circadian_rhythm_and_sleep_timing",
    name: "Circadian Rhythm and Sleep Timing",
    domain: "health",
    description:
      "Where the creator weighs in on Circadian Rhythm and Sleep Timing.",
    aliases: [
      "circadian",
      "rhythm sleep",
      "sleep timing",
      "circadian rhythm",
      "rhythm sleep timing",
      "circadian rhythm sleep",
      "circadian rhythm and sleep timing",
    ],
  },
  {
    slug: "cortisol_stress_and_burnout",
    name: "Cortisol Stress and Burnout",
    domain: "health",
    description: "Analysis and commentary on Cortisol Stress and Burnout.",
    aliases: [
      "cortisol",
      "high cortisol",
      "stress burnout",
      "cortisol levels",
      "cortisol stress",
      "cortisol stress burnout",
      "cortisol stress and burnout",
    ],
  },
  {
    slug: "diet_categories",
    name: "Diet Categories",
    domain: "health",
    description: "Segments that dig into Diet Categories.",
    aliases: [
      "stop shop",
      "different diet",
      "diet categories",
      "delivered doorstep",
      "intermittent fasting",
    ],
  },
  {
    slug: "eating_disorders_and_food_reward",
    name: "Eating Disorders and Food Reward",
    domain: "health",
    description: "Conversations and takes on Eating Disorders and Food Reward.",
    aliases: [
      "food reward",
      "disorders food",
      "eating disorders",
      "disorders food reward",
      "eating disorders food",
      "eating disorders and food reward",
    ],
  },
  {
    slug: "education_school_policy",
    name: "Education School Policy",
    domain: "politics",
    description: "Where the creator weighs in on Education School Policy.",
    aliases: ["education school policy"],
  },
  {
    slug: "emotional_intelligence_and_emotion_regulation",
    name: "Emotional Intelligence and Emotion Regulation",
    domain: "health",
    description:
      "Analysis and commentary on Emotional Intelligence and Emotion Regulation.",
    aliases: [
      "emotion regulation",
      "intelligence emotion",
      "emotional intelligence",
      "emotional intelligence emotion",
      "intelligence emotion regulation",
      "emotional intelligence and emotion regulation",
    ],
  },
  {
    slug: "error_based_learning_and_neuroplasticity",
    name: "Error Based Learning and Neuroplasticity",
    domain: "health",
    description:
      "Segments that dig into Error Based Learning and Neuroplasticity.",
    aliases: [
      "error based",
      "making errors",
      "based learning",
      "error based learning",
      "learning neuroplasticity",
      "based learning neuroplasticity",
      "error based learning and neuroplasticity",
    ],
  },
  {
    slug: "estrogen_hormone_health",
    name: "Estrogen Hormone Health",
    domain: "health",
    description: "Conversations and takes on Estrogen Hormone Health.",
    aliases: ["estrogen hormone health"],
  },
  {
    slug: "family_relationships",
    name: "Family Relationships",
    domain: "health",
    description: "Where the creator weighs in on Family Relationships.",
    aliases: ["family relationships"],
  },
  {
    slug: "family_relationships_and_attachment",
    name: "Family Relationships and Attachment",
    domain: "health",
    description:
      "Analysis and commentary on Family Relationships and Attachment.",
    aliases: [
      "mom dad",
      "family relationships",
      "relationships attachment",
      "family relationships attachment",
      "family relationships and attachment",
    ],
  },
  {
    slug: "gene_therapy",
    name: "Gene Therapy",
    domain: "health",
    description: "Segments that dig into Gene Therapy.",
    aliases: ["gene editing", "gene therapy"],
  },
  {
    slug: "goal_setting_and_visual_attention",
    name: "Goal Setting and Visual Attention",
    domain: "health",
    description:
      "Conversations and takes on Goal Setting and Visual Attention.",
    aliases: [
      "goal pursuit",
      "goal setting",
      "goal setting visual",
      "goal setting and visual attention",
    ],
  },
  {
    slug: "gut_microbiome",
    name: "Gut Health",
    domain: "health",
    description: "Where the creator weighs in on Gut Health.",
    aliases: [
      "gut biome",
      "gut brain",
      "gut health",
      "microbiome",
      "gut barrier",
      "bacteria gut",
      "gut microbiome",
    ],
  },
  {
    slug: "healthcare_system_reform",
    name: "Healthcare System Reform",
    domain: "health",
    description: "Analysis and commentary on Healthcare System Reform.",
    aliases: [
      "health care",
      "system reform",
      "healthcare system",
      "healthcare system reform",
    ],
  },
  {
    slug: "high_cortisol",
    name: "High Cortisol",
    domain: "health",
    description: "Segments that dig into High Cortisol.",
    aliases: ["cortisol", "cortisol high", "high cortisol", "cortisol levels"],
  },
  {
    slug: "immune_system_and_cold_flu_prevention",
    name: "Immune System and Cold Flu Prevention",
    domain: "health",
    description:
      "Conversations and takes on Immune System and Cold Flu Prevention.",
    aliases: [
      "cold flu",
      "system cold",
      "immune system",
      "innate immune",
      "flu prevention",
      "adaptive immune",
      "system cold flu",
      "immune system cold",
      "cold flu prevention",
      "immune system and cold flu prevention",
    ],
  },
  {
    slug: "insulin_resistance",
    name: "Blood Glucose",
    domain: "health",
    description: "Where the creator weighs in on Blood Glucose.",
    aliases: [
      "glucose",
      "insulin",
      "beta cell",
      "beta cells",
      "blood sugar",
      "blood glucose",
      "type diabetes",
      "glucose levels",
      "glucose monitor",
      "pancreatic beta",
      "glucose tolerance",
      "continuous glucose",
      "insulin resistance",
      "cardiovascular disease",
    ],
  },
  {
    slug: "jiu_jitsu",
    name: "Jiu Jitsu",
    domain: "health",
    description: "Analysis and commentary on Jiu Jitsu.",
    aliases: ["jiu jitsu", "push pull", "imagine scenario"],
  },
  {
    slug: "lactate_threshold_and_zone_2_training",
    name: "Lactate Threshold and Zone 2 Training",
    domain: "health",
    description:
      "Segments that dig into Lactate Threshold and Zone 2 Training.",
    aliases: [
      "zone 2",
      "lactate",
      "2 training",
      "lactic acid",
      "threshold zone",
      "zone 2 training",
      "threshold zone 2",
      "lactate threshold",
      "lactate threshold zone",
      "lactate threshold and zone 2 training",
    ],
  },
  {
    slug: "ldl_cholesterol",
    name: "LDL Cholesterol",
    domain: "health",
    description: "Conversations and takes on LDL Cholesterol.",
    aliases: ["ldl", "cholesterol", "oxidized ldl", "ldl cholesterol"],
  },
  {
    slug: "learning_memory_and_study_protocols",
    name: "Learning Memory and Study Protocols",
    domain: "health",
    description:
      "Where the creator weighs in on Learning Memory and Study Protocols.",
    aliases: [
      "memory study",
      "trying learn",
      "skill learning",
      "learning memory",
      "study protocols",
      "learning memory study",
      "memory study protocols",
      "learning memory and study protocols",
    ],
  },
  {
    slug: "maple_syrup",
    name: "Maple Syrup",
    domain: "health",
    description: "Analysis and commentary on Maple Syrup.",
    aliases: ["maple syrup", "sugar maple", "regular sugar"],
  },
  {
    slug: "melatonin_sleep_supplements",
    name: "Melatonin Sleep Supplements",
    domain: "health",
    description: "Segments that dig into Melatonin Sleep Supplements.",
    aliases: ["melatonin sleep supplements"],
  },
  {
    slug: "menopause_hormone_health",
    name: "Menopause Hormone Health",
    domain: "health",
    description: "Conversations and takes on Menopause Hormone Health.",
    aliases: ["menopause hormone health"],
  },
  {
    slug: "mitochondrial_health",
    name: "Mitochondrial Health",
    domain: "health",
    description: "Where the creator weighs in on Mitochondrial Health.",
    aliases: ["mitochondrial health"],
  },
  {
    slug: "mobility_posture_and_lower_body_mechanics",
    name: "Mobility Posture and Lower Body Mechanics",
    domain: "health",
    description:
      "Analysis and commentary on Mobility Posture and Lower Body Mechanics.",
    aliases: [
      "hip leg",
      "lower body",
      "posture lower",
      "body mechanics",
      "mobility posture",
      "posture lower body",
      "lower body mechanics",
      "mobility posture lower",
      "mobility posture and lower body mechanics",
    ],
  },
  {
    slug: "molasses_and_glycemic_control",
    name: "Molasses and Glycemic Control",
    domain: "health",
    description: "Segments that dig into Molasses and Glycemic Control.",
    aliases: [
      "sugar molasses",
      "gastric emptying",
      "glycemic control",
      "molasses glycemic",
      "molasses glycemic control",
      "molasses and glycemic control",
    ],
  },
  {
    slug: "motor_neurons_and_spinal_cord_function",
    name: "Motor Neurons and Spinal Cord Function",
    domain: "health",
    description:
      "Conversations and takes on Motor Neurons and Spinal Cord Function.",
    aliases: [
      "spinal cord",
      "cord function",
      "motor neurons",
      "neurons spinal",
      "neurons spinal cord",
      "motor neurons spinal",
      "spinal cord function",
      "motor neurons and spinal cord function",
    ],
  },
  {
    slug: "neuroplasticity_learning",
    name: "Neuroplasticity Learning",
    domain: "health",
    description: "Where the creator weighs in on Neuroplasticity Learning.",
    aliases: ["neuroplasticity learning"],
  },
  {
    slug: "neuroscience_explainers",
    name: "Neuroscience Explainers",
    domain: "health",
    description: "Analysis and commentary on Neuroscience Explainers.",
    aliases: ["neuroscience explainers"],
  },
  {
    slug: "opioid_use_and_addiction",
    name: "Opioid Use and Addiction",
    domain: "health",
    description: "Segments that dig into Opioid Use and Addiction.",
    aliases: ["opioid use and addiction"],
  },
  {
    slug: "oral_health_and_fluoride",
    name: "Oral Health and Fluoride",
    domain: "health",
    description: "Conversations and takes on Oral Health and Fluoride.",
    aliases: [
      "fluoride",
      "oral health",
      "health fluoride",
      "oral health fluoride",
      "oral health and fluoride",
    ],
  },
  {
    slug: "oxytocin_and_social_bonding",
    name: "Oxytocin and Social Bonding",
    domain: "health",
    description: "Where the creator weighs in on Oxytocin and Social Bonding.",
    aliases: [
      "oxytocin",
      "oxytocin going",
      "social bonding",
      "oxytocin social",
      "oxytocin social bonding",
      "oxytocin and social bonding",
    ],
  },
  {
    slug: "parenting_child_development",
    name: "Parenting Child Development",
    domain: "health",
    description: "Analysis and commentary on Parenting Child Development.",
    aliases: ["parenting child development"],
  },
  {
    slug: "pcos_endometriosis_and_fertility",
    name: "Pcos Endometriosis and Fertility",
    domain: "health",
    description: "Segments that dig into Pcos Endometriosis and Fertility.",
    aliases: ["pcos endometriosis and fertility"],
  },
  {
    slug: "placebo_effects",
    name: "Placebo Effects",
    domain: "health",
    description: "Conversations and takes on Placebo Effects.",
    aliases: ["placebo", "belief effects", "placebo effect", "placebo effects"],
  },
  {
    slug: "police_use_of_force_and_reform",
    name: "Police Use of Force and Reform",
    domain: "politics",
    description:
      "Where the creator weighs in on Police Use of Force and Reform.",
    aliases: [
      "use force",
      "police use",
      "force reform",
      "police unions",
      "police use force",
      "use force reform",
      "police use of force and reform",
    ],
  },
  {
    slug: "pre_and_post_workout_nutrition",
    name: "Pre and Post Workout Nutrition",
    domain: "health",
    description: "Analysis and commentary on Pre and Post Workout Nutrition.",
    aliases: [
      "pre post",
      "pre workout",
      "post workout",
      "workout meal",
      "pre post workout",
      "workout nutrition",
      "post workout nutrition",
      "pre and post workout nutrition",
    ],
  },
  {
    slug: "prescription_drug_safety",
    name: "Prescription Drug Safety",
    domain: "health",
    description: "Segments that dig into Prescription Drug Safety.",
    aliases: ["prescription drug safety"],
  },
  {
    slug: "protein_intake",
    name: "Protein Intake",
    domain: "health",
    description: "Conversations and takes on Protein Intake.",
    aliases: ["protein intake"],
  },
  {
    slug: "psilocybin_therapy_and_psychedelic_experience",
    name: "Psilocybin Therapy and Psychedelic Experience",
    domain: "health",
    description:
      "Where the creator weighs in on Psilocybin Therapy and Psychedelic Experience.",
    aliases: [
      "psilocybin",
      "psychedelic",
      "psilocybin journey",
      "psilocybin therapy",
      "therapy psychedelic",
      "psychedelic experience",
      "psilocybin therapy psychedelic",
      "therapy psychedelic experience",
      "psilocybin therapy and psychedelic experience",
    ],
  },
  {
    slug: "psychedelic_therapy_and_clinical_trials",
    name: "Psychedelic Therapy and Clinical Trials",
    domain: "health",
    description:
      "Analysis and commentary on Psychedelic Therapy and Clinical Trials.",
    aliases: [
      "psychedelic",
      "clinical trials",
      "therapy clinical",
      "psychedelic therapy",
      "therapy clinical trials",
      "psychedelic therapy clinical",
      "psychedelic therapy and clinical trials",
    ],
  },
  {
    slug: "public_health_trust_and_science_policy",
    name: "Public Health Trust and Science Policy",
    domain: "health",
    description:
      "Segments that dig into Public Health Trust and Science Policy.",
    aliases: [
      "health trust",
      "public health",
      "trust science",
      "science policy",
      "public health trust",
      "health trust science",
      "trust science policy",
      "public health trust and science policy",
    ],
  },
  {
    slug: "raw_milk",
    name: "Raw Milk",
    domain: "health",
    description: "Conversations and takes on Raw Milk.",
    aliases: ["raw milk", "milk protein"],
  },
  {
    slug: "relationship_psychology_and_attachment",
    name: "Relationship Psychology and Attachment",
    domain: "health",
    description:
      "Where the creator weighs in on Relationship Psychology and Attachment.",
    aliases: [
      "psychology attachment",
      "relationship psychology",
      "relationship psychology attachment",
      "relationship psychology and attachment",
    ],
  },
  {
    slug: "reproductive_hormone_health",
    name: "Reproductive Hormone Health",
    domain: "health",
    description: "Analysis and commentary on Reproductive Hormone Health.",
    aliases: ["reproductive hormone health"],
  },
  {
    slug: "sex_hormones_and_behavior",
    name: "Sex Hormones and Behavior",
    domain: "health",
    description: "Segments that dig into Sex Hormones and Behavior.",
    aliases: ["sex hormones and behavior"],
  },
  {
    slug: "sex_hormones_and_sexual_development",
    name: "Sex Hormones and Sexual Development",
    domain: "health",
    description:
      "Conversations and takes on Sex Hormones and Sexual Development.",
    aliases: [
      "sex hormones",
      "hormones sexual",
      "sexual behavior",
      "sexual development",
      "sex hormones sexual",
      "hormones sexual development",
      "sex hormones and sexual development",
    ],
  },
  {
    slug: "speech_language_and_communication_neuroscience",
    name: "Speech Language and Communication Neuroscience",
    domain: "health",
    description:
      "Where the creator weighs in on Speech Language and Communication Neuroscience.",
    aliases: [
      "speech language",
      "language communication",
      "communication neuroscience",
      "speech language communication",
      "language communication neuroscience",
      "speech language and communication neuroscience",
    ],
  },
  {
    slug: "ssri_and_antidepressant_use",
    name: "SSRI and Antidepressant Use",
    domain: "health",
    description: "Analysis and commentary on SSRI and Antidepressant Use.",
    aliases: [
      "serotonin",
      "levels serotonin",
      "antidepressant use",
      "dopamine serotonin",
      "increase serotonin",
      "ssri antidepressant",
      "ssri antidepressant use",
      "ssri and antidepressant use",
    ],
  },
  {
    slug: "strength_training",
    name: "Strength Training",
    domain: "health",
    description: "Segments that dig into Strength Training.",
    aliases: ["strength training"],
  },
  {
    slug: "substance_and_behavioral_addiction_recovery",
    name: "Substance and Behavioral Addiction Recovery",
    domain: "health",
    description:
      "Conversations and takes on Substance and Behavioral Addiction Recovery.",
    aliases: [
      "substance use",
      "addiction recovery",
      "behavioral addiction",
      "substance behavioral",
      "behavioral addiction recovery",
      "substance behavioral addiction",
      "substance and behavioral addiction recovery",
    ],
  },
  {
    slug: "testosterone_and_hormone_optimization",
    name: "Testosterone and Hormone Optimization",
    domain: "health",
    description:
      "Where the creator weighs in on Testosterone and Hormone Optimization.",
    aliases: [
      "testosterone",
      "testosterone levels",
      "hormone optimization",
      "testosterone hormone",
      "increase testosterone",
      "testosterone hormone optimization",
      "testosterone and hormone optimization",
    ],
  },
  {
    slug: "testosterone_optimization",
    name: "Testosterone Optimization",
    domain: "health",
    description: "Analysis and commentary on Testosterone Optimization.",
    aliases: ["testosterone optimization"],
  },
  {
    slug: "use_cannabis",
    name: "Cannabis Use and Legalization",
    domain: "health",
    description: "Segments that dig into Cannabis Use and Legalization.",
    aliases: [
      "thc",
      "cannabis",
      "marijuana",
      "cannabis use",
      "use cannabis",
      "use legalization",
      "cannabis use legalization",
      "cannabis use and legalization",
    ],
  },
  {
    slug: "visceral_fat_and_metabolic_health",
    name: "Visceral Fat and Metabolic Health",
    domain: "health",
    description:
      "Conversations and takes on Visceral Fat and Metabolic Health.",
    aliases: [
      "visceral fat",
      "fat metabolic",
      "metabolic health",
      "fat metabolic health",
      "visceral fat metabolic",
      "visceral fat and metabolic health",
    ],
  },
  {
    slug: "vision_and_eye_health",
    name: "Vision and Eye Health",
    domain: "health",
    description: "Where the creator weighs in on Vision and Eye Health.",
    aliases: [
      "eye health",
      "vision eye",
      "eye movements",
      "smooth pursuit",
      "vision eye health",
      "vision and eye health",
    ],
  },
  {
    slug: "vitamin_d_supplementation",
    name: "Vitamin Levels",
    domain: "health",
    description: "Analysis and commentary on Vitamin Levels.",
    aliases: [
      "vitamin",
      "cod liver",
      "liver oil",
      "vitamin d",
      "vitamin levels",
      "vitamin vitamin",
      "d supplementation",
      "synthetic vitamin",
      "vitamin d supplementation",
    ],
  },
  {
    slug: "academy_awards_and_oscar_races",
    name: "Academy Awards and Oscar Races",
    domain: "media",
    description: "Segments that dig into Academy Awards and Oscar Races.",
    aliases: [
      "oscar",
      "oscar races",
      "awards oscar",
      "best picture",
      "academy awards",
      "awards oscar races",
      "academy awards oscar",
      "academy awards and oscar races",
    ],
  },
  {
    slug: "alien_and_predator_franchise_films",
    name: "Alien and Predator Franchise Films",
    domain: "media",
    description:
      "Conversations and takes on Alien and Predator Franchise Films.",
    aliases: [
      "alien versus",
      "alien romulus",
      "alien predator",
      "franchise films",
      "versus predator",
      "predator badlands",
      "predator franchise",
      "alien predator franchise",
      "predator franchise films",
      "alien and predator franchise films",
    ],
  },
  {
    slug: "apple_tv_plus_streaming_strategy",
    name: "Apple TV Plus Streaming Strategy",
    domain: "media",
    description:
      "Where the creator weighs in on Apple TV Plus Streaming Strategy.",
    aliases: [
      "tv plus",
      "apple tv",
      "apple watch",
      "tv streaming",
      "apple tv streaming",
      "streaming strategy",
      "tv streaming strategy",
      "apple tv plus streaming strategy",
    ],
  },
  {
    slug: "deadpool_and_wolverine_film",
    name: "Deadpool and Wolverine Film",
    domain: "media",
    description: "Analysis and commentary on Deadpool and Wolverine Film.",
    aliases: ["deadpool and wolverine film"],
  },
  {
    slug: "disney_animated_film_releases",
    name: "Disney Animated Film Releases",
    domain: "media",
    description: "Segments that dig into Disney Animated Film Releases.",
    aliases: [
      "disney",
      "quite good",
      "moana going",
      "moana moana",
      "animated film",
      "film releases",
      "streamed movie",
      "disney animated",
      "disney animated film",
      "animated film releases",
      "disney animated film releases",
    ],
  },
  {
    slug: "disney_leadership_and_corporate_strategy",
    name: "Disney Leadership and Corporate Strategy",
    domain: "media",
    description:
      "Conversations and takes on Disney Leadership and Corporate Strategy.",
    aliases: [
      "disney",
      "bob chek",
      "bob iger",
      "bob chapek",
      "disney leadership",
      "corporate strategy",
      "leadership corporate",
      "disney leadership corporate",
      "leadership corporate strategy",
      "disney leadership and corporate strategy",
    ],
  },
  {
    slug: "doctor_doom_mcu_casting",
    name: "Doctor Doom MCU Casting",
    domain: "media",
    description: "Where the creator weighs in on Doctor Doom MCU Casting.",
    aliases: ["doctor doom mcu casting"],
  },
  {
    slug: "film_characters_casting_and_performances",
    name: "Film Characters Casting and Performances",
    domain: "media",
    description:
      "Analysis and commentary on Film Characters Casting and Performances.",
    aliases: [
      "film characters",
      "characters casting",
      "casting performances",
      "film characters casting",
      "characters casting performances",
      "film characters casting and performances",
    ],
  },
  {
    slug: "film_music_awards",
    name: "Film Music Awards",
    domain: "media",
    description: "Segments that dig into Film Music Awards.",
    aliases: ["film music awards"],
  },
  {
    slug: "film_production_and_screenwriting",
    name: "Film Production and Screenwriting",
    domain: "media",
    description:
      "Conversations and takes on Film Production and Screenwriting.",
    aliases: [
      "film production",
      "script production",
      "production screenwriting",
      "film production screenwriting",
      "film production and screenwriting",
    ],
  },
  {
    slug: "hollywood_casting_and_franchise_news",
    name: "Hollywood Casting and Franchise News",
    domain: "media",
    description:
      "Where the creator weighs in on Hollywood Casting and Franchise News.",
    aliases: [
      "boy henry",
      "john wick",
      "henry caval",
      "franchise news",
      "casting franchise",
      "hollywood casting",
      "casting franchise news",
      "hollywood casting franchise",
      "hollywood casting and franchise news",
    ],
  },
  {
    slug: "hollywood_studio_mergers",
    name: "Hollywood Studio Mergers",
    domain: "media",
    description: "Analysis and commentary on Hollywood Studio Mergers.",
    aliases: ["hollywood studio mergers"],
  },
  {
    slug: "horror_film_franchise_reviews",
    name: "Horror Film Franchise Reviews",
    domain: "media",
    description: "Segments that dig into Horror Film Franchise Reviews.",
    aliases: [
      "horror film",
      "megan megan",
      "megan movie",
      "lethal weapon",
      "nights freddy",
      "film franchise",
      "franchise reviews",
      "horror film franchise",
      "film franchise reviews",
      "horror film franchise reviews",
    ],
  },
  {
    slug: "house_of_the_dragon_series",
    name: "House of the Dragon Series",
    domain: "media",
    description: "Conversations and takes on House of the Dragon Series.",
    aliases: ["house of the dragon series"],
  },
  {
    slug: "how_to_train_your_dragon_films",
    name: "How to Train Your Dragon Films",
    domain: "media",
    description:
      "Where the creator weighs in on How to Train Your Dragon Films.",
    aliases: ["how to train your dragon films"],
  },
  {
    slug: "hugh_jackman_as_wolverine",
    name: "Hugh Jackman As Wolverine",
    domain: "media",
    description: "Analysis and commentary on Hugh Jackman As Wolverine.",
    aliases: ["hugh jackman as wolverine"],
  },
  {
    slug: "imax_screens_and_premium_theater_formats",
    name: "IMAX Screens and Premium Theater Formats",
    domain: "media",
    description:
      "Segments that dig into IMAX Screens and Premium Theater Formats.",
    aliases: [
      "imax",
      "imax screen",
      "getting imax",
      "imax screens",
      "premium theater",
      "screens premium",
      "theater formats",
      "imax screens premium",
      "premium theater formats",
      "screens premium theater",
      "imax screens and premium theater formats",
    ],
  },
  {
    slug: "iron_man_and_tony_stark_mcu",
    name: "Iron Man and Tony Stark MCU",
    domain: "media",
    description: "Conversations and takes on Iron Man and Tony Stark MCU.",
    aliases: ["iron man and tony stark mcu"],
  },
  {
    slug: "iron_man_films",
    name: "Iron Man Films",
    domain: "media",
    description: "Where the creator weighs in on Iron Man Films.",
    aliases: ["iron man films"],
  },
  {
    slug: "karate_kid_and_cobra_kai_franchise",
    name: "Karate Kid and Cobra Kai Franchise",
    domain: "media",
    description:
      "Analysis and commentary on Karate Kid and Cobra Kai Franchise.",
    aliases: [
      "cobra kai",
      "kid cobra",
      "karate kid",
      "kai franchise",
      "kid cobra kai",
      "karate kid cobra",
      "cobra kai franchise",
      "karate kid and cobra kai franchise",
    ],
  },
  {
    slug: "legacy_media_and_journalism_bias",
    name: "Legacy Media and Journalism Bias",
    domain: "media",
    description: "Segments that dig into Legacy Media and Journalism Bias.",
    aliases: [
      "new york",
      "york city",
      "york times",
      "legacy media",
      "journalism bias",
      "washington post",
      "media journalism",
      "media journalism bias",
      "legacy media journalism",
      "legacy media and journalism bias",
    ],
  },
  {
    slug: "live_action_remakes",
    name: "Live Action Remakes",
    domain: "media",
    description: "Conversations and takes on Live Action Remakes.",
    aliases: ["live action remakes"],
  },
  {
    slug: "mcu_actor_returns",
    name: "MCU Actor Returns",
    domain: "media",
    description: "Where the creator weighs in on MCU Actor Returns.",
    aliases: ["mcu actor returns"],
  },
  {
    slug: "mcu_casting_and_actor_returns",
    name: "MCU Casting and Actor Returns",
    domain: "media",
    description: "Analysis and commentary on MCU Casting and Actor Returns.",
    aliases: ["mcu casting and actor returns"],
  },
  {
    slug: "mcu_character_legacy",
    name: "MCU Character Legacy",
    domain: "media",
    description: "Segments that dig into MCU Character Legacy.",
    aliases: ["mcu character legacy"],
  },
  {
    slug: "mcu_doctor_strange_films",
    name: "MCU Doctor Strange Films",
    domain: "media",
    description: "Conversations and takes on MCU Doctor Strange Films.",
    aliases: [
      "mcu",
      "mcu doctor",
      "emergency kit",
      "strange films",
      "doctor strange",
      "medical emergency",
      "mcu doctor strange",
      "multiverse madness",
      "strange multiverse",
      "doctor strange films",
      "mcu doctor strange films",
    ],
  },
  {
    slug: "mcu_post_credit_scenes",
    name: "MCU Post Credit Scenes",
    domain: "media",
    description: "Where the creator weighs in on MCU Post Credit Scenes.",
    aliases: [
      "mcu",
      "mcu post",
      "post credit",
      "credit scenes",
      "mcu post credit",
      "post credit scenes",
      "mcu post credit scenes",
    ],
  },
  {
    slug: "michael_b_jordan_performances",
    name: "Michael B Jordan Performances",
    domain: "media",
    description: "Analysis and commentary on Michael B Jordan Performances.",
    aliases: ["michael b jordan performances"],
  },
  {
    slug: "mission_impossible_films",
    name: "Mission Impossible Films",
    domain: "media",
    description: "Segments that dig into Mission Impossible Films.",
    aliases: ["mission impossible films"],
  },
  {
    slug: "movie_and_tv_runtime_discussion",
    name: "Movie and TV Runtime Discussion",
    domain: "media",
    description: "Conversations and takes on Movie and TV Runtime Discussion.",
    aliases: [
      "movie tv",
      "10 minutes",
      "30 minutes",
      "tv runtime",
      "movie tv runtime",
      "runtime discussion",
      "tv runtime discussion",
      "movie and tv runtime discussion",
    ],
  },
  {
    slug: "movie_box_office",
    name: "Movie Box Office",
    domain: "media",
    description: "Where the creator weighs in on Movie Box Office.",
    aliases: ["movie box", "box office", "second weekend", "movie box office"],
  },
  {
    slug: "movie_budgets_and_studio_profitability",
    name: "Movie Budgets and Studio Profitability",
    domain: "media",
    description:
      "Analysis and commentary on Movie Budgets and Studio Profitability.",
    aliases: [
      "100 million",
      "200 million",
      "400 million",
      "movie budgets",
      "budgets studio",
      "movie budgets studio",
      "studio profitability",
      "budgets studio profitability",
      "movie budgets and studio profitability",
    ],
  },
  {
    slug: "movie_reviews_and_opinions",
    name: "Movie Reviews and Opinions",
    domain: "media",
    description: "Segments that dig into Movie Reviews and Opinions.",
    aliases: ["movie reviews and opinions"],
  },
  {
    slug: "movie_theater_chains_and_ticket_pricing",
    name: "Movie Theater Chains and Ticket Pricing",
    domain: "media",
    description:
      "Conversations and takes on Movie Theater Chains and Ticket Pricing.",
    aliases: [
      "amc theaters",
      "chains ticket",
      "movie theater",
      "theater chains",
      "ticket pricing",
      "movie theater chains",
      "chains ticket pricing",
      "theater chains ticket",
      "movie theater chains and ticket pricing",
    ],
  },
  {
    slug: "movie_trailers_and_theatrical_marketing",
    name: "Movie Trailers and Theatrical Marketing",
    domain: "media",
    description:
      "Where the creator weighs in on Movie Trailers and Theatrical Marketing.",
    aliases: [
      "movie starts",
      "movie trailers",
      "trailers movie",
      "trailers theatrical",
      "theatrical marketing",
      "movie trailers theatrical",
      "trailers theatrical marketing",
      "movie trailers and theatrical marketing",
    ],
  },
  {
    slug: "music_neuroscience",
    name: "Music Neuroscience",
    domain: "media",
    description: "Analysis and commentary on Music Neuroscience.",
    aliases: ["listen music", "listening music", "music neuroscience"],
  },
  {
    slug: "music_streaming_technology",
    name: "Music Streaming Technology",
    domain: "media",
    description: "Segments that dig into Music Streaming Technology.",
    aliases: ["music streaming technology"],
  },
  {
    slug: "obi_wan_kenobi_series",
    name: "Obi Wan Kenobi Series",
    domain: "media",
    description: "Conversations and takes on Obi Wan Kenobi Series.",
    aliases: ["obi wan kenobi series"],
  },
  {
    slug: "peacemaker_series_reviews",
    name: "Peacemaker Series Reviews",
    domain: "media",
    description: "Where the creator weighs in on Peacemaker Series Reviews.",
    aliases: ["peacemaker series reviews"],
  },
  {
    slug: "robert_downey_jr_performances",
    name: "Robert Downey Jr Performances",
    domain: "media",
    description: "Analysis and commentary on Robert Downey Jr Performances.",
    aliases: ["robert downey jr performances"],
  },
  {
    slug: "ryan_coogler_films",
    name: "Ryan Coogler Films",
    domain: "media",
    description: "Segments that dig into Ryan Coogler Films.",
    aliases: ["ryan coogler films"],
  },
  {
    slug: "shrek_and_dreamworks_franchise_films",
    name: "Shrek and DreamWorks Franchise Films",
    domain: "media",
    description:
      "Conversations and takes on Shrek and DreamWorks Franchise Films.",
    aliases: [
      "shrek",
      "far far",
      "far away",
      "mike myers",
      "puss boots",
      "shrek film",
      "boots movie",
      "franchise films",
      "shrek dreamworks",
      "dreamworks franchise",
      "dreamworks franchise films",
      "shrek dreamworks franchise",
      "shrek and dreamworks franchise films",
    ],
  },
  {
    slug: "sinners_film_reviews",
    name: "Sinners Film Reviews",
    domain: "media",
    description: "Where the creator weighs in on Sinners Film Reviews.",
    aliases: ["sinners film reviews"],
  },
  {
    slug: "sony_spider_man_universe_films",
    name: "Sony Spider-Man Universe Films",
    domain: "media",
    description: "Analysis and commentary on Sony Spider-Man Universe Films.",
    aliases: [
      "madam web",
      "spider man",
      "sony spider",
      "man universe",
      "universe films",
      "sony spider man",
      "man universe films",
      "spider man universe",
      "sony spider man universe films",
    ],
  },
  {
    slug: "star_wars_canon_and_jedi_lore",
    name: "Star Wars Canon and Jedi Lore",
    domain: "media",
    description: "Segments that dig into Star Wars Canon and Jedi Lore.",
    aliases: ["star wars canon and jedi lore"],
  },
  {
    slug: "star_wars_disney_plus_series",
    name: "Star Wars Disney Plus Series",
    domain: "media",
    description: "Conversations and takes on Star Wars Disney Plus Series.",
    aliases: [
      "best star",
      "star wars",
      "tony gilroy",
      "wars disney",
      "andor season",
      "disney series",
      "original trilogy",
      "star wars disney",
      "wars disney series",
      "star wars disney plus series",
    ],
  },
  {
    slug: "streaming_strategy",
    name: "Streaming Strategy",
    domain: "media",
    description: "Where the creator weighs in on Streaming Strategy.",
    aliases: ["streaming strategy"],
  },
  {
    slug: "streaming_tv_series_reviews",
    name: "Streaming TV Series Reviews",
    domain: "media",
    description: "Analysis and commentary on Streaming TV Series Reviews.",
    aliases: [
      "ted lasso",
      "tv series",
      "streaming tv",
      "harrison ford",
      "season finale",
      "series finale",
      "series reviews",
      "tv series reviews",
      "streaming tv series",
      "streaming tv series reviews",
    ],
  },
  {
    slug: "superhero_movies",
    name: "Superhero Movies",
    domain: "media",
    description: "Segments that dig into Superhero Movies.",
    aliases: ["superhero movies"],
  },
  {
    slug: "television_awards_and_emmy_races",
    name: "Television Awards and Emmy Races",
    domain: "media",
    description: "Conversations and takes on Television Awards and Emmy Races.",
    aliases: [
      "emmy",
      "going win",
      "emmy races",
      "awards emmy",
      "awards emmy races",
      "television awards",
      "television awards emmy",
      "television awards and emmy races",
    ],
  },
  {
    slug: "the_boys_tv_series_reviews",
    name: "The Boys TV Series Reviews",
    domain: "media",
    description: "Where the creator weighs in on The Boys TV Series Reviews.",
    aliases: [
      "boys tv",
      "bad boys",
      "tv series",
      "soldier boy",
      "boys tv series",
      "series reviews",
      "tv series reviews",
      "the boys tv series reviews",
    ],
  },
  {
    slug: "tony_stark_character",
    name: "Tony Stark Character",
    domain: "media",
    description: "Analysis and commentary on Tony Stark Character.",
    aliases: ["tony stark character"],
  },
  {
    slug: "transformers_and_hasbro_franchise_films",
    name: "Transformers and Hasbro Franchise Films",
    domain: "media",
    description:
      "Segments that dig into Transformers and Hasbro Franchise Films.",
    aliases: [
      "gi joe",
      "michael bay",
      "travis knight",
      "franchise films",
      "hasbro franchise",
      "best transformers",
      "transformers movie",
      "transformers hasbro",
      "transformers movies",
      "hasbro franchise films",
      "transformers hasbro franchise",
      "transformers and hasbro franchise films",
    ],
  },
  {
    slug: "tv_season_finales",
    name: "TV Season Finales",
    domain: "media",
    description: "Conversations and takes on TV Season Finales.",
    aliases: ["tv season finales"],
  },
  {
    slug: "visual_effects_industry",
    name: "Visual Effects Industry",
    domain: "media",
    description: "Where the creator weighs in on Visual Effects Industry.",
    aliases: ["effects industry", "visual effects industry"],
  },
  {
    slug: "warner_bros_studio",
    name: "Warner Bros Studio",
    domain: "media",
    description: "Analysis and commentary on Warner Bros Studio.",
    aliases: ["warner bros studio"],
  },
  {
    slug: "wicked_movie_musical_reviews",
    name: "Wicked Movie Musical Reviews",
    domain: "media",
    description: "Segments that dig into Wicked Movie Musical Reviews.",
    aliases: [
      "wizard oz",
      "wicked good",
      "cynthia revo",
      "wicked movie",
      "ariana grande",
      "movie musical",
      "musical reviews",
      "wicked movie musical",
      "movie musical reviews",
      "wicked movie musical reviews",
    ],
  },
  {
    slug: "california_business_and_tax_policy",
    name: "California Business and Tax Policy",
    domain: "politics",
    description:
      "Conversations and takes on California Business and Tax Policy.",
    aliases: ["california business and tax policy"],
  },
  {
    slug: "california_housing_policy",
    name: "California Housing Policy",
    domain: "politics",
    description: "Where the creator weighs in on California Housing Policy.",
    aliases: ["california housing policy"],
  },
  {
    slug: "california_union_policy",
    name: "California Union Policy",
    domain: "politics",
    description: "Analysis and commentary on California Union Policy.",
    aliases: ["california union policy"],
  },
  {
    slug: "federal_budget_and_national_debt",
    name: "Federal Budget and National Debt",
    domain: "politics",
    description: "Segments that dig into Federal Budget and National Debt.",
    aliases: [
      "half trillion",
      "national debt",
      "trillion year",
      "federal budget",
      "budget national",
      "trillion dollar",
      "trillion dollars",
      "budget national debt",
      "federal budget national",
      "federal budget and national debt",
    ],
  },
  {
    slug: "gavin_newsom_governorship",
    name: "Gavin Newsom Governorship",
    domain: "politics",
    description: "Conversations and takes on Gavin Newsom Governorship.",
    aliases: ["gavin newsom governorship"],
  },
  {
    slug: "minimum_wage_and_labor_policy",
    name: "Minimum Wage and Labor Policy",
    domain: "politics",
    description:
      "Where the creator weighs in on Minimum Wage and Labor Policy.",
    aliases: [
      "fast food",
      "bucks hour",
      "wage labor",
      "labor policy",
      "minimum wage",
      "raise minimum",
      "wage labor policy",
      "minimum wage labor",
      "minimum wage and labor policy",
    ],
  },
  {
    slug: "trump_economic_policy",
    name: "Trump Economic Policy",
    domain: "politics",
    description: "Analysis and commentary on Trump Economic Policy.",
    aliases: ["trump economic policy"],
  },
  {
    slug: "trump_tech_ai_policy",
    name: "Trump Tech AI Policy",
    domain: "politics",
    description: "Segments that dig into Trump Tech AI Policy.",
    aliases: ["trump tech ai policy"],
  },
  {
    slug: "trump_trade_policy",
    name: "Trump Trade Policy",
    domain: "politics",
    description: "Conversations and takes on Trump Trade Policy.",
    aliases: ["trump trade policy"],
  },
  {
    slug: "5g_network_performance",
    name: "5G Network Performance",
    domain: "technology",
    description: "Where the creator weighs in on 5G Network Performance.",
    aliases: [
      "band 5g",
      "5g phone",
      "5g network",
      "millimeter wave",
      "network performance",
      "5g network performance",
    ],
  },
  {
    slug: "ai_agents",
    name: "AI Agents",
    domain: "technology",
    description: "Analysis and commentary on AI Agents.",
    aliases: ["ai agents", "open claw"],
  },
  {
    slug: "ai_data_center_infrastructure",
    name: "AI Data Center Infrastructure",
    domain: "technology",
    description: "Segments that dig into AI Data Center Infrastructure.",
    aliases: [
      "ai data",
      "data center",
      "data centers",
      "ai data center",
      "data center infrastructure",
      "ai data center infrastructure",
    ],
  },
  {
    slug: "ai_investment_bubble",
    name: "AI Investment Bubble",
    domain: "technology",
    description: "Conversations and takes on AI Investment Bubble.",
    aliases: ["ai investment bubble"],
  },
  {
    slug: "ai_model_competition",
    name: "AI Model Competition",
    domain: "technology",
    description: "Where the creator weighs in on AI Model Competition.",
    aliases: ["ai model", "model competition", "ai model competition"],
  },
  {
    slug: "ai_safety_mental_health",
    name: "AI Safety Mental Health",
    domain: "technology",
    description: "Analysis and commentary on AI Safety Mental Health.",
    aliases: ["ai safety mental health"],
  },
  {
    slug: "ai_societal_impact",
    name: "Artificial Intelligence",
    domain: "technology",
    description: "Segments that dig into Artificial Intelligence.",
    aliases: [
      "ai societal",
      "societal impact",
      "ai societal impact",
      "artificial intelligence",
    ],
  },
  {
    slug: "airpods_and_earbuds_reviews",
    name: "AirPods and Earbuds Reviews",
    domain: "technology",
    description: "Conversations and takes on AirPods and Earbuds Reviews.",
    aliases: [
      "airpods",
      "airpods pro",
      "new airpods",
      "airpods earbuds",
      "earbuds reviews",
      "airpods earbuds reviews",
      "airpods and earbuds reviews",
    ],
  },
  {
    slug: "android_os_and_software_updates",
    name: "Android OS and Software Updates",
    domain: "technology",
    description:
      "Where the creator weighs in on Android OS and Software Updates.",
    aliases: [
      "android",
      "android os",
      "os software",
      "android phone",
      "stock android",
      "android phones",
      "version android",
      "software updates",
      "android os software",
      "os software updates",
      "android os and software updates",
    ],
  },
  {
    slug: "app_store_antitrust_and_platform_policy",
    name: "App Store Antitrust and Platform Policy",
    domain: "technology",
    description:
      "Analysis and commentary on App Store Antitrust and Platform Policy.",
    aliases: [
      "app stores",
      "platform policy",
      "store antitrust",
      "antitrust platform",
      "app store antitrust",
      "store antitrust platform",
      "antitrust platform policy",
      "app store antitrust and platform policy",
    ],
  },
  {
    slug: "apple_ai_strategy_and_apple_intelligence",
    name: "Apple AI Strategy and Apple Intelligence",
    domain: "technology",
    description:
      "Segments that dig into Apple AI Strategy and Apple Intelligence.",
    aliases: [
      "apple ai",
      "tim cook",
      "ai strategy",
      "apple silicon",
      "strategy apple",
      "ai strategy apple",
      "apple ai strategy",
      "apple intelligence",
      "strategy apple intelligence",
      "apple ai strategy and apple intelligence",
    ],
  },
  {
    slug: "apple_mac_reviews",
    name: "Apple Mac Reviews",
    domain: "technology",
    description: "Conversations and takes on Apple Mac Reviews.",
    aliases: ["apple mac reviews"],
  },
  {
    slug: "apple_silicon_mac_performance",
    name: "Apple Silicon Mac Performance",
    domain: "technology",
    description:
      "Where the creator weighs in on Apple Silicon Mac Performance.",
    aliases: [
      "m1 max",
      "silicon mac",
      "apple silicon",
      "mac performance",
      "apple silicon mac",
      "silicon mac performance",
      "apple silicon mac performance",
    ],
  },
  {
    slug: "apple_watch_reviews",
    name: "Apple Watch Reviews",
    domain: "technology",
    description: "Analysis and commentary on Apple Watch Reviews.",
    aliases: ["apple watch reviews"],
  },
  {
    slug: "budget_android_smartphones",
    name: "Budget Android Smartphones",
    domain: "technology",
    description: "Segments that dig into Budget Android Smartphones.",
    aliases: [
      "android",
      "end device",
      "moto style",
      "near stock",
      "camera moto",
      "stock android",
      "budget android",
      "android smartphones",
      "budget android smartphones",
    ],
  },
  {
    slug: "chip_supply_chain",
    name: "Chip Supply Chain",
    domain: "technology",
    description:
      "Conversations and takes on the semiconductor chip supply chain.",
    aliases: [
      "chip supply",
      "supply chain",
      "chip supply chain",
      "semiconductor supply",
    ],
  },
  {
    slug: "cinema_camera_tech",
    name: "Cinema Camera Tech",
    domain: "technology",
    description: "Where the creator weighs in on Cinema Camera Tech.",
    aliases: ["cinema camera tech"],
  },
  {
    slug: "compact_camera_reviews",
    name: "Compact Camera Reviews",
    domain: "technology",
    description: "Analysis and commentary on Compact Camera Reviews.",
    aliases: [
      "mark iii",
      "rx100 mark",
      "frames second",
      "pocket camera",
      "camera reviews",
      "compact camera",
      "compact camera reviews",
    ],
  },
  {
    slug: "computer_mouse_and_peripheral_reviews",
    name: "Computer Mouse and Peripheral Reviews",
    domain: "technology",
    description:
      "Segments that dig into Computer Mouse and Peripheral Reviews.",
    aliases: [
      "mx master",
      "magic mouse",
      "scroll wheel",
      "computer mouse",
      "mouse peripheral",
      "peripheral reviews",
      "mouse peripheral reviews",
      "computer mouse peripheral",
      "computer mouse and peripheral reviews",
    ],
  },
  {
    slug: "consumer_drone_technology",
    name: "Consumer Drone Technology",
    domain: "technology",
    description: "Conversations and takes on Consumer Drone Technology.",
    aliases: [
      "drone",
      "consumer drone",
      "drone delivery",
      "drone technology",
      "consumer drone technology",
    ],
  },
  {
    slug: "crypto_bitcoin",
    name: "Crypto Bitcoin",
    domain: "technology",
    description: "Where the creator weighs in on Crypto Bitcoin.",
    aliases: ["crypto bitcoin"],
  },
  {
    slug: "custom_android_roms",
    name: "Custom Android ROMs",
    domain: "technology",
    description: "Analysis and commentary on Custom Android ROMs.",
    aliases: [
      "android",
      "cyan mod",
      "engine mod",
      "android roms",
      "cyanogen mod",
      "stock android",
      "custom android",
      "custom android roms",
    ],
  },
  {
    slug: "flagship_smartphone_reviews",
    name: "Flagship Smartphone Reviews",
    domain: "technology",
    description: "Segments that dig into Flagship Smartphone Reviews.",
    aliases: [
      "flagship phone",
      "flagship smartphone",
      "flagship smartphone reviews",
    ],
  },
  {
    slug: "foldable_smartphone_reviews",
    name: "Foldable Smartphone Reviews",
    domain: "technology",
    description: "Conversations and takes on Foldable Smartphone Reviews.",
    aliases: [
      "foldable",
      "foldables",
      "galaxy fold",
      "escobar fold",
      "galaxy folds",
      "samsung galaxy",
      "folding phone",
      "folding phones",
      "foldable smartphone",
      "foldable smartphone reviews",
    ],
  },
  {
    slug: "gaming_smartphones",
    name: "Gaming Smartphones",
    domain: "technology",
    description: "Where the creator weighs in on Gaming Smartphones.",
    aliases: [
      "rog phone",
      "gaming phone",
      "gaming phones",
      "gaming smartphones",
    ],
  },
  {
    slug: "generative_ai_creativity",
    name: "Generative AI Creativity",
    domain: "technology",
    description: "Analysis and commentary on Generative AI Creativity.",
    aliases: ["generative ai creativity"],
  },
  {
    slug: "google_play_edition_devices",
    name: "Google Play Edition Devices",
    domain: "technology",
    description: "Segments that dig into Google Play Edition Devices.",
    aliases: [
      "play store",
      "google play",
      "play edition",
      "edition phone",
      "edition devices",
      "google play edition",
      "play edition devices",
      "google play edition devices",
    ],
  },
  {
    slug: "gut_brain_axis",
    name: "Gut-Brain Axis",
    domain: "health",
    description: "Conversations and takes on Gut-Brain Axis.",
    aliases: ["gut brain", "brain axis", "gut brain axis"],
  },
  {
    slug: "happiness_and_wellbeing_psychology",
    name: "Happiness and Wellbeing Psychology",
    domain: "health",
    description:
      "Where the creator weighs in on Happiness and Wellbeing Psychology.",
    aliases: [
      "agency gratitude",
      "happiness wellbeing",
      "wellbeing psychology",
      "happiness wellbeing psychology",
      "happiness and wellbeing psychology",
    ],
  },
  {
    slug: "huawei_ban_and_android_geopolitics",
    name: "Huawei Ban and Android Geopolitics",
    domain: "technology",
    description:
      "Analysis and commentary on Huawei Ban and Android Geopolitics.",
    aliases: [
      "20 pro",
      "android",
      "mate 20",
      "p20 pro",
      "p30 pro",
      "huawei ban",
      "ban android",
      "huawei ban android",
      "android geopolitics",
      "ban android geopolitics",
      "huawei ban and android geopolitics",
    ],
  },
  {
    slug: "iphone_reviews",
    name: "iPhone Reviews",
    domain: "technology",
    description: "Segments that dig into iPhone Reviews.",
    aliases: [
      "11 pro",
      "12 pro",
      "13 pro",
      "14 pro",
      "ios 12",
      "iphone",
      "10s 10s",
      "10s max",
      "6s plus",
      "pro max",
      "3d touch",
      "ipad pro",
      "iphone 10",
      "iphone 11",
      "iphone 12",
      "iphone 13",
      "iphone 14",
      "iphone 15",
      "iphone 6s",
      "pro phone",
      "a15 bionic",
      "iphone 10r",
      "iphone 10s",
      "new iphone",
      "night mode",
      "pro phones",
      "ultra wide",
      "force touch",
      "iphone plus",
      "iphone iphone",
      "iphone reviews",
    ],
  },
  {
    slug: "keyboard_and_computer_peripheral_reviews",
    name: "Keyboard and Computer Peripheral Reviews",
    domain: "technology",
    description:
      "Conversations and takes on Keyboard and Computer Peripheral Reviews.",
    aliases: [
      "keyboard app",
      "keyboard computer",
      "peripheral reviews",
      "computer peripheral",
      "computer peripheral reviews",
      "keyboard computer peripheral",
      "keyboard and computer peripheral reviews",
    ],
  },
  {
    slug: "mac_mini_reviews",
    name: "Mac Mini Reviews",
    domain: "technology",
    description: "Where the creator weighs in on Mac Mini Reviews.",
    aliases: ["mac mini reviews"],
  },
  {
    slug: "oneplus_smartphone_reviews",
    name: "OnePlus Smartphone Reviews",
    domain: "technology",
    description: "Analysis and commentary on OnePlus Smartphone Reviews.",
    aliases: [
      "oneplus",
      "oxygen os",
      "oneplus pro",
      "oneplus smartphone",
      "oneplus smartphone reviews",
    ],
  },
  {
    slug: "open_source_ai_models",
    name: "Open Source AI Models",
    domain: "technology",
    description: "Segments that dig into Open Source AI Models.",
    aliases: ["open source ai models"],
  },
  {
    slug: "openai_company",
    name: "OpenAI Company",
    domain: "technology",
    description: "Conversations and takes on OpenAI Company.",
    aliases: ["openai company"],
  },
  {
    slug: "product_red_iphone",
    name: "Product Red Iphone",
    domain: "technology",
    description: "Where the creator weighs in on Product Red Iphone.",
    aliases: ["product red iphone"],
  },
  {
    slug: "right_to_repair",
    name: "Right to Repair",
    domain: "technology",
    description: "Analysis and commentary on Right to Repair.",
    aliases: ["body shop", "repair shops", "right repair", "right to repair"],
  },
  {
    slug: "samsung_galaxy_s_reviews",
    name: "Samsung Galaxy S Reviews",
    domain: "technology",
    description: "Segments that dig into Samsung Galaxy S Reviews.",
    aliases: [
      "galaxy",
      "s9 plus",
      "samsung",
      "galaxy s",
      "galaxy s8",
      "galaxy s9",
      "s reviews",
      "bixby button",
      "samsung galaxy",
      "galaxy s reviews",
      "samsung galaxy s",
      "samsung galaxy s reviews",
    ],
  },
  {
    slug: "selfie_and_front_camera_design",
    name: "Selfie and Front Camera Design",
    domain: "technology",
    description: "Conversations and takes on Selfie and Front Camera Design.",
    aliases: [
      "hole punch",
      "ultra wide",
      "front camera",
      "selfie front",
      "camera design",
      "selfie camera",
      "front camera design",
      "selfie front camera",
      "selfie and front camera design",
    ],
  },
  {
    slug: "smartphone_awards",
    name: "Smartphone Awards",
    domain: "technology",
    description: "Where the creator weighs in on Smartphone Awards.",
    aliases: ["bust year", "smartphone awards"],
  },
  {
    slug: "smartphone_battery_technology",
    name: "Smartphone Battery Technology",
    domain: "technology",
    description: "Analysis and commentary on Smartphone Battery Technology.",
    aliases: [
      "000 mah",
      "battery",
      "charger",
      "charging",
      "batteries",
      "battery life",
      "fast charging",
      "battery health",
      "carbon battery",
      "silicon carbon",
      "battery technology",
      "smartphone battery",
      "smartphone battery technology",
    ],
  },
  {
    slug: "smartphone_bezel_and_notch_design",
    name: "Smartphone Bezel and Notch Design",
    domain: "technology",
    description: "Segments that dig into Smartphone Bezel and Notch Design.",
    aliases: [
      "pixel xl",
      "hide notch",
      "hole punch",
      "bezel notch",
      "notch design",
      "facing camera",
      "essential phone",
      "smartphone bezel",
      "bezel notch design",
      "smartphone bezel notch",
      "smartphone bezel and notch design",
    ],
  },
  {
    slug: "smartphone_camera_technology",
    name: "Smartphone Camera Technology",
    domain: "technology",
    description: "Conversations and takes on Smartphone Camera Technology.",
    aliases: [
      "dual cameras",
      "camera technology",
      "smartphone camera",
      "mirrorless cameras",
      "smartphone cameras",
      "smartphone camera technology",
    ],
  },
  {
    slug: "smartphone_concept_phone_hype",
    name: "Smartphone Concept Phone Hype",
    domain: "technology",
    description:
      "Where the creator weighs in on Smartphone Concept Phone Hype.",
    aliases: [
      "phone hype",
      "concept phone",
      "concept phone hype",
      "smartphone concept",
      "research development",
      "smartphone concept phone",
      "smartphone concept phone hype",
    ],
  },
  {
    slug: "smartphone_oem_industry",
    name: "Smartphone OEM Industry",
    domain: "technology",
    description: "Analysis and commentary on Smartphone OEM Industry.",
    aliases: [
      "lg g2",
      "lg g3",
      "lg skin",
      "oem industry",
      "motorola phone",
      "smartphone oem",
      "google motorola",
      "google financial",
      "smartphone oem industry",
    ],
  },
  {
    slug: "smartphone_telephoto_and_optical_zoom",
    name: "Smartphone Telephoto and Optical Zoom",
    domain: "technology",
    description:
      "Segments that dig into Smartphone Telephoto and Optical Zoom.",
    aliases: [
      "zoom hd",
      "digital zoom",
      "optical zoom",
      "telephoto camera",
      "telephoto optical",
      "smartphone telephoto",
      "telephoto optical zoom",
      "smartphone telephoto optical",
      "smartphone telephoto and optical zoom",
    ],
  },
  {
    slug: "smartwatch_and_wearable_reviews",
    name: "Smartwatch and Wearable Reviews",
    domain: "technology",
    description: "Conversations and takes on Smartwatch and Wearable Reviews.",
    aliases: [
      "moto 360",
      "android wear",
      "android weare",
      "wearable reviews",
      "smartwatch wearable",
      "smartwatch wearable reviews",
      "smartwatch and wearable reviews",
    ],
  },
  {
    slug: "social_media_and_dopamine_addiction",
    name: "Social Media and Dopamine Addiction",
    domain: "technology",
    description:
      "Where the creator weighs in on Social Media and Dopamine Addiction.",
    aliases: [
      "dopamine",
      "dopamine hit",
      "dopamine hits",
      "media dopamine",
      "increase dopamine",
      "dopamine addiction",
      "dopamine receptors",
      "social media dopamine",
      "media dopamine addiction",
      "social media and dopamine addiction",
    ],
  },
  {
    slug: "sony_xperia_enthusiast_phones",
    name: "Sony Xperia Enthusiast Phones",
    domain: "technology",
    description: "Analysis and commentary on Sony Xperia Enthusiast Phones.",
    aliases: [
      "sony phone",
      "inch sensor",
      "sony xperia",
      "xperia mark",
      "enthusiast phones",
      "xperia enthusiast",
      "sony xperia enthusiast",
      "xperia enthusiast phones",
      "sony xperia enthusiast phones",
    ],
  },
  {
    slug: "tech_and_fashion_brand_collaborations",
    name: "Tech and Fashion Brand Collaborations",
    domain: "technology",
    description:
      "Segments that dig into Tech and Fashion Brand Collaborations.",
    aliases: [
      "gucci xbox",
      "xbox series",
      "tech fashion",
      "fashion brand",
      "tech fashion brand",
      "brand collaborations",
      "fashion brand collaborations",
      "tech and fashion brand collaborations",
    ],
  },
  {
    slug: "tv_and_display_technology",
    name: "TV and Display Technology",
    domain: "technology",
    description: "Conversations and takes on TV and Display Technology.",
    aliases: [
      "hdmi ports",
      "tv display",
      "display technology",
      "tv display technology",
      "tv and display technology",
    ],
  },
  {
    slug: "windows_phone_and_nokia_lumia",
    name: "Windows Phone and Nokia Lumia",
    domain: "technology",
    description:
      "Where the creator weighs in on Windows Phone and Nokia Lumia.",
    aliases: [
      "lumia 1020",
      "nokia lumia",
      "phone nokia",
      "41 megapixel",
      "windows phone",
      "phone nokia lumia",
      "windows phone nokia",
      "windows phone and nokia lumia",
    ],
  },
];

/*
 * Flat list of just the controlled taxonomy's display names, handed to the
 * LLM topic-detection prompt as the candidate vocabulary.
 */
export const DEFAULT_TOPIC_TAXONOMY = CONTROLLED_TOPIC_TAXONOMY.map(
  (topic) => topic.name,
);

const TAXONOMY_BY_SLUG = new Map(
  CONTROLLED_TOPIC_TAXONOMY.map((e) => [e.slug, e]),
);

/** Generic words that carry no topic signal, dropped from the keyword set. */
const KEYWORD_STOPWORDS = new Set([
  "and",
  "the",
  "of",
  "to",
  "in",
  "on",
  "for",
  "with",
  "reviews",
  "review",
  "policy",
  "strategy",
  "crisis",
  "markets",
  "market",
  "design",
  "performance",
  "technology",
  "races",
  "treatment",
  "competition",
  "infrastructure",
  "optimization",
]);

/**
 * Distinctive lowercased keywords for a topic — its name tokens plus taxonomy
 * aliases, minus generic stopwords — used to score whether an evidence quote is
 * actually ON that topic. Falls back to name tokens when the slug is unknown.
 */
export function topicKeywords(slug: string, name: string): string[] {
  const entry = TAXONOMY_BY_SLUG.get(slug);
  const phrases = [name, ...(entry?.aliases ?? [])];
  const out = new Set<string>();
  for (const phrase of phrases) {
    for (const w of phrase.toLowerCase().split(/\s+/)) {
      const clean = w.replace(/[^a-z0-9]/g, "");
      if (clean.length >= 4 && !KEYWORD_STOPWORDS.has(clean)) out.add(clean);
    }
  }
  return [...out];
}
